food/foodproject/foodhub/urls.py
from django.urls import path
from . import views
app_name='foodhub'
urlpatterns=[
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail')
]

food/foodproject/foodproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from foodhub import views
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home'),
    path('',include('foodhub.urls')),
    path('search/',include('search_app.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

food/foodproject/search_app/urls.py
from django.urls import path
from . import views

app_name = "search_app"

urlpatterns=[
    path('searchResult',views.searchResult,name='searchResult'),

]

food/foodproject/foodhub/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    desc=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse("foodhub:products_by_category",args=[self.slug])

    def __str__(self):
            return '{}'.format(self.name)


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    image = models.ImageField(upload_to='product', blank=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def get_url(self):
        return reverse("foodhub:ProdCatDetail",args=[self.category.slug,self.slug])

    def __str__(self):
            return '{}'.format(self.name)

food/foodproject/search_app/models.py
from django.db import models

# Create your models here.

food/foodproject/foodhub/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.
def home(request):
    return HttpResponse("helloo")



def allProdCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug!=None:
        c_page = get_object_or_404(Category,slug=c_slug)
        products_list = Product.objects.filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,3)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page,'products':products})

def ProdCatDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

food/foodproject/search_app/views.py
from django.shortcuts import render
from foodhub.models import Product
from django.db.models import Q
# Create your views here.
def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
    return render(request,"search.html",{'query':query,'products':products})

food/foodproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>


</head>
<body>
<div>
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

food/foodproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
    {{ category.desc |truncatewords:155 }}
   {% else %}
     welcome to the foodhub online restuarant where you order delicious food items.
   {% endif %}
{% endblock %}
{% block title %}
  {% if category %}
     {{category.name}}-foodhub
  {% else %}
     see our food items -foodhub
  {% endif %}
{% endblock %}
{% block content %}
  {% if category %}
    <div class="row my_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'foodhub:allProdCat' %}">food items we serve </a>{{ category.name }}</p>
        </div>
    </div>
  {% endif %}
<div class="mx-auto">
      {% if category %}
         <img class="my_image" src="{{category.image.url}}" alt="{{ category.name}}">
</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
      {% else %}
       <div>
           <centre><img class="my_image my_image_padding" src="{% static 'img/foodbanner.png' %}" alt=""style="width:1300px;"></centre>
       </div>
<br>
       <div>
           <h1 class="text-center my_title">food items we serve</h1><br>
           <p class="text-justify">Order food online from Food hub. Choose from a wide range of cuisines and categories for food delivery. Get fresh home delivered food at your doorstep from Food hub.

.....you wish we serve...</p>


       </div>
      {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div  class="card text-center" style="width: 18rem;">
             <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url}}" alt="{{product.name}}" style="width:250px;height:250px"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>${{product.price}}</p>
            </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
        </div>
    </div>
{% endblock %}

food/foodproject/templates/footer.html
{% load static %}

<div>
    <centre><img class="my_image my_image_padding" src="{% static 'img/footer.jpg' %}" alt=""style="width:1350px;"></centre>
</div>
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Food Hub Online Restuarant.All Rights Reserved</p>
</div>

food/foodproject/templates/header.html
{% load static %}
<div>
    <center>
        <img src="{% static 'img/foodlogo.png' %}" alt="this is foodhub logo">
    </center>
</div>

food/foodproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<!--  <a class="navbar-brand" href="#">Navbar</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
             <li class="nav-item dropdown ">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
             food items
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'foodhub:allProdCat' %}">All food items</a>
            {% for cat in links %}
            <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
        </div>
             </li>
<!--
          <div class="dropdown-divider"></div>
-->
<!--
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
-->
<!--
        </div>
-->
<!--
             </ul>
-->
  <!--</div>-->


<!--
    {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="cart:cart_details"><i class="fas fa-cart-plus">{{item_count}}</i></a>
      </li>
    {% endif %}
{% if user.is_authenticated %}
        <li class="nav-item active"><a class="nav-link">Hai {{user.username}}</a></li>
        <li class="nav-item active">
        <a class="nav-link" href="accounts/logout">logout <span class="sr-only">(current)</span></a>
-->
<!--
        </li>
        {% else %}
        <li class="nav-item active">
        <a class="nav-link" href="accounts/register">register <span class="sr-only">(current)</span></a>
        </li>
-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->

    </ul>


<!--
      <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><a href="accounts/login">login <span class="sr-only">(current)</span></a></li>
      </ul>
-->
<!--
      {% endif %}
-->
      <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get" >
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="Search Recipies" aria-label="Search " name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
  </div>
</nav>

<!--
<nav>
    <ul>
        <li><a href="{% url 'foodhub:allProdCat' %}">All products</a> </li>
        {% for cat in links %}
            <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
        {% endfor %}
        <li><a href="">Your order</a> </li>
-->

<!--
    </ul>
</nav>-->

food/foodproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.desc |truncatewords:155 }}
{% endblock %}
{% block title %}
     {{product.name}}-foodhub
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a href="{% url 'foodhub:allProdCat' %}">Home</a><a href="{{product.category.get_url}}"></a>{{product.name}}</p>
    </div>
    <div>
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="width:250px;height:250px">
                <img src="{{product.image.url}}"alt="{{product.name}}" style="width:250px;height:250px">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title"> {{product.name}}</h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text_justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                <p class="text_justify my_prod_text"><b>Out of stock</b></p>
                {% else %}
                <a class="btn btn-secondary" href="">Order Now</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

food/foodproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product.desc | truncatewords:155 }}
{% endblock %}
{% block title %}
     {{product.name}}-foodhub
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> you have searched for:{{query}} </p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div  class="card text-center" style="width: 18rem;">
             <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{ product.image.url}}" alt="{{product.name}}"></a>
            <div class="card-body">
                <h4>{{product.name}}</h4>
                <p>${{product.price}}</p>
            </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text"> 0 results found. </p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}